import type { HelpCategory } from "./types";

export const glosario: HelpCategory = {
  slug: "glosario",
  title: "Glosario",
  articles: [
    {
      slug: "glosario",
      title: "Glosario de términos",
      summary:
        "Qué significa cada palabra técnica o de negocio que aparece en el panel: de API key a zona catch-all.",
      audience: "both",
      keywords: ["diccionario", "términos", "definiciones", "qué significa", "vocabulario"],
      body: [
        {
          type: "p",
          text:
            "Los términos están en orden alfabético. Si una palabra del panel no aparece aquí, búscala con " +
            "el buscador de la izquierda: casi todas se explican dentro de su guía.",
        },
        {
          type: "glossary",
          items: [
            { term: "Agente", definition: "El programa automático que contesta a tus clientes por WhatsApp usando tu catálogo real. No es una persona." },
            { term: "API", definition: "La vía por la que un programa le pide cosas a otro. Atiende ya tiene una API para que otros sistemas consulten o cambien tu información." },
            { term: "API key", definition: "Una contraseña hecha para programas, no para personas. Empieza con npk_ y solo puede hacer lo que sus permisos (scopes) le dejan." },
            { term: "Archivar", definition: "Dar de baja algo sin borrarlo. Un producto o cliente archivado deja de usarse, pero su historial se conserva y se puede restaurar." },
            { term: "Bitácora de auditoría", definition: "El registro automático de quién cambió qué y cuándo. Nadie la edita a mano. La ves en Admin → Seguridad → Actividad." },
            { term: "Borrador (DRAFT)", definition: "Algo que todavía se está preparando. Un producto en borrador no se vende; una cotización en borrador todavía no tiene precios fijos." },
            { term: "Canal", definition: "Un número de WhatsApp conectado a tu negocio. Puede conectarse por Evolution (con QR) o por Meta (API oficial)." },
            { term: "Catch-all", definition: "La zona de envío que aplica cuando la dirección del cliente no cae en ninguna otra zona. Solo puede haber una." },
            { term: "CFDI", definition: "Comprobante Fiscal Digital por Internet: el nombre oficial de la factura electrónica en México." },
            { term: "Checkout", definition: "La pantalla donde el cliente revisa su pedido y paga. Se abre con el link de pago." },
            { term: "Clave SAT", definition: "Códigos que el SAT pide en las facturas: clave de producto (8 dígitos) y clave de unidad (por ejemplo H87 = pieza)." },
            { term: "Cobro rápido", definition: "Cobrar un monto libre con un concepto escrito a mano, sin catálogo ni cotización." },
            { term: "Conocimiento", definition: "Los documentos con información de tu negocio (horarios, políticas, preguntas frecuentes) que el agente consulta para contestar." },
            { term: "Consentimiento", definition: "El permiso que un cliente te da para contactarlo o usar sus datos. Se guarda en su ficha." },
            { term: "Constancia de situación fiscal", definition: "Un PDF que el SAT da a cada contribuyente con su RFC, nombre o razón social, código postal y régimen fiscal. Con subirla basta para pedir factura." },
            { term: "Cotización", definition: "Una propuesta de compra con productos, cantidades y total, todavía sin pagar." },
            { term: "CSV", definition: "Un archivo de texto con datos en columnas separadas por comas. Excel y Google Sheets lo pueden guardar. Sirve para importar el catálogo." },
            { term: "Emitir", definition: "Dejar una cotización lista para el cliente: sus precios quedan fijos y empieza a correr su vigencia." },
            { term: "Escalar (handoff)", definition: "Cuando el agente pasa una conversación a una persona de tu equipo. Mientras una persona la atiende, el agente no contesta." },
            { term: "Existencia (stock)", definition: "Cuántas unidades tienes para vender de una variante. Si la dejas vacía, esa variante no lleva control de inventario." },
            { term: "Idempotencia", definition: "Una protección para que repetir la misma acción (por ejemplo, dar dos clics en Cobrar) no genere dos cobros." },
            { term: "IVA", definition: "Impuesto al valor agregado. Se configura en Admin → Empresa y se suma a cotizaciones y pedidos nuevos." },
            { term: "Libro de movimientos (ledger)", definition: "La lista, en orden, de cargos y reembolsos de un cobro, con el saldo después de cada uno." },
            { term: "Link público", definition: "Una dirección web que el cliente abre sin cuenta ni contraseña: la de una cotización, la de pago o la de seguimiento de pedido." },
            { term: "MCP", definition: "Model Context Protocol: un idioma común para que asistentes de inteligencia artificial, como Claude, usen tu cuenta como herramienta." },
            { term: "Modelo (de IA)", definition: "El \"cerebro\" que redacta las respuestas del agente. Se elige en Consola del agente → General → Modelo." },
            { term: "Modo de pruebas", definition: "Estado en el que los pagos son simulados y no se mueve dinero real. Se reconoce por la etiqueta \"Pruebas\"." },
            { term: "Pedido", definition: "La venta que resulta de aceptar una cotización o de un cobro rápido. Tiene su propio estado: por pagar, pagado, entregado, cancelado…" },
            { term: "Prefijo", definition: "La parte visible de una API key (npk_…). Sirve para reconocerla, pero no para usarla." },
            { term: "Razón social", definition: "El nombre legal a nombre de quien se factura. Puede ser distinto del nombre con el que conoces al cliente." },
            { term: "Reembolso", definition: "Devolver al cliente todo o parte de lo que pagó." },
            { term: "Régimen fiscal", definition: "La clave de 3 números con la que el SAT clasifica a un contribuyente (por ejemplo 626 = Régimen Simplificado de Confianza). Viene en la constancia." },
            { term: "RFC", definition: "Registro Federal de Contribuyentes: 13 caracteres para personas físicas y 12 para empresas." },
            { term: "Rol", definition: "El conjunto de permisos de una persona en tu empresa: qué ve y qué puede cambiar." },
            { term: "SAT", definition: "Servicio de Administración Tributaria: la autoridad de impuestos de México." },
            { term: "Scope (permiso)", definition: "La autorización para hacer una sola cosa concreta, por ejemplo \"ver catálogo\" o \"reembolsar pagos\"." },
            { term: "Sesión de pago", definition: "Un intento de cobro con monto y moneda, ligado a un pedido." },
            { term: "SKU", definition: "Un código corto y único para identificar un producto o una variante, como el número de un código de barras." },
            { term: "SPEI", definition: "El sistema de transferencias bancarias de México. El cliente puede pagar así desde el link de pago." },
            { term: "Tenant (empresa)", definition: "Cada negocio que usa Atiende ya. Tus datos están separados de los de cualquier otra empresa." },
            { term: "Token", definition: "En el agente, la unidad con la que se mide cuánto texto lee y escribe el modelo. Más tokens = más costo." },
            { term: "Transcripción", definition: "Convertir una nota de voz en texto. El agente transcribe los audios de WhatsApp antes de contestar." },
            { term: "Uso de CFDI", definition: "Un código que dice para qué se usará la factura, por ejemplo G03 (gastos en general). La constancia no lo trae: lo elige el cliente." },
            { term: "Variante", definition: "Una versión concreta de un producto (talla, color, tamaño) con su propio SKU, precio y existencia." },
            { term: "Verificación en dos pasos (MFA)", definition: "Un segundo candado para tu cuenta: además de la contraseña, un código de 6 números de una app en tu celular." },
            { term: "Vigencia", definition: "Cuánto tiempo sirve algo antes de vencer: una cotización, un link de pago o un cobro rápido." },
            { term: "Webhook", definition: "El aviso automático que un sistema le manda a otro cuando pasa algo. Así llegan los mensajes de WhatsApp al panel." },
            { term: "Zona de envío", definition: "Un área (por código postal, ciudad o estado) con su propio precio de envío a domicilio." },
          ],
        },
      ],
      related: ["que-es-atiende-ya", "recorrido-del-panel"],
    },
  ],
};
